spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: create   # pour ne pas recr�er la base � chaque d�marrage
    show-sql: true        # pour voir les requ�tes SQL dans la console
    properties:
      hibernate:
        format_sql: true  # pour que les requ�tes soient jolies
    open-in-view: false   # d�sactive l'avertissement open-in-view